// Code generated by gst; DO NOT EDIT.
package router

import (
	"aichat/model/example"

	"github.com/forbearing/gst/router"
	"github.com/forbearing/gst/types"
	"github.com/forbearing/gst/types/consts"
)

func Init() error {
	router.Register[*example.Event, *example.Event, *example.Event](router.Auth(), "event", &types.ControllerConfig[*example.Event]{}, consts.List)
	return nil
}
