// Code generated by gst; DO NOT EDIT.
package service

import (
	"aichat/service/example/event"

	"github.com/forbearing/gst/service"
	"github.com/forbearing/gst/types/consts"
)

func init() {
	service.Register[*event.Lister](consts.PHASE_LIST)
}
