// Code generated by gst; DO NOT EDIT.
package main

import (
	_ "aichat/configx"
	_ "aichat/cronjob"
	_ "aichat/middleware"
	_ "aichat/model"
	_ "aichat/module"
	"aichat/router"
	_ "aichat/service"

	"github.com/forbearing/gst/bootstrap"
	. "github.com/forbearing/gst/util"
)

func main() {
	RunOrDie(bootstrap.Bootstrap)
	RunOrDie(router.Init)
	RunOrDie(bootstrap.Run)
}
