// Code generated by gst; DO NOT EDIT.
package model

import (
	"demo/model/setting"

	"github.com/forbearing/gst/model"
)

func init() {
	model.Register[*setting.Project]()
	model.Register[*setting.Region]()
	model.Register[*setting.Tenant]()
	model.Register[*setting.Vendor]()
}
